defaults:
  - _self_
  - override hydra/launcher: submitit_local

port: 12235

### DMC Pretraining Data
offline_data_dir: null
task_names: [acrobot_swingup, finger_turn_hard, hopper_stand, walker_run, humanoid_stand, dog_walk]

### Replay Buffer
replay_buffer_num_workers: 1
n_traj: 1000
nstep: 3
batch_size: 4096

### Misc
seed: 1
device: cuda
use_tb: false
frame_stack: 3
action_repeat: 2

### agent
target: premier_taco.PremierTACORepresentation
lr: 1e-4
num_train_steps: 100000
feature_dim: 100
exp_name: default
window_size: 5
save_snapshot: true

agent:
  _target_: ${target}
  obs_shape: ??? # to be specified later
  action_shapes: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  nstep: ${nstep}


hydra:
  run:
    dir: ./exp_local/${exp_name}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm

